name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Stats SVG
        run: |
          mkdir -p github-stats
          curl -L -H "User-Agent: Mozilla/5.0" -o github-stats/github-stats.svg "https://github-readme-stats.vercel.app/api?username=vmosque&show_icons=true&theme=tokyonight&cache_seconds=1800"
          curl -L -H "User-Agent: Mozilla/5.0" -o github-stats/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=vmosque&layout=compact&theme=tokyonight&cache_seconds=1800"

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-stats/*
          git commit -m "update stats" || echo "No changes"
          git push
